package Repo;

import org.json.JSONException;
import org.json.JSONObject;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class WeatherRepo {

    private Service service;

    public WeatherRepo(Service service) {
        this.service = service;
    }

    public Double getTemperatureAtTheMoment() {
        try {
            return service.findData().getJSONObject("main").getDouble("temp");
        } catch (JSONException e1) {
            e1.printStackTrace();
        }
        return null;
    }

    public String getCurrentCity() {
        try {
            return service.findData().getString("name");
        } catch (JSONException e1) {
            e1.printStackTrace();
        }
        return "";
    }

    public String getCoordinates() {

        try {

            JSONObject coord = service.findData().getJSONObject("coord");
            return "lon: " + coord.getDouble("lon") + ", lat: " + coord.getDouble("lat");

        } catch (JSONException e1) {
            e1.printStackTrace();
        }
        return null;
    }

    public JSONObject getJsonObject() {
        return service.findData();
    }
}
   
	