package Repo;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;

import org.json.JSONException;
import org.json.JSONObject;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class WeatherRepo {
	
	private String city;
	private JSONObject jsonObject;
	
	public WeatherRepo(String city) {
		
		this.city = city;
		
		String apiUrl = "http://api.openweathermap.org/data/2.5/weather?q=" + this.city + "&units=metric&appid=472668130148f8ffc32aaba1c58267f6";
		

	
	try {

		URL url = new URL(apiUrl);
		HttpURLConnection conn = (HttpURLConnection) url.openConnection();
		conn.connect();

		BufferedReader br = new BufferedReader(new InputStreamReader(
			(conn.getInputStream())));
		StringBuilder sb = new StringBuilder();

		String output;
		while ((output = br.readLine()) != null) {
			sb.append(output).append("\n");
		}

		conn.disconnect();
		
		jsonObject = new JSONObject(sb.toString());

	  } catch (JSONException e1) {

		e1.printStackTrace();

	  } catch (IOException e1) {

		e1.printStackTrace();

	  }

	}

	

    public Double getTemperatureAtTheMoment() {
        try {
            return jsonObject.getJSONObject("main").getDouble("temp");
        } catch (JSONException e1) {
        	e1.printStackTrace();
        }
        return null;
    }

    public String getCurrentCity() {
        try {
            return jsonObject.getString("name");
        } catch (JSONException e1) {
            e1.printStackTrace();
        }
        return "";
    }


}
   
	