package Test;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import Repo.ForecastRepo;
import Repo.WeatherRepo;

import static org.junit.Assert.*;

import org.json.JSONException;
import org.json.JSONObject;
import org.junit.Before;

public class WeatherTest {
	
	WeatherRepo weather;
	WeatherRepo weatherAtTheMoment;
	
	ForecastRepo forecast;
	ForecastRepo forecastAtTheMoment;
   
    @Before
    public void startBeforeEeachTest() {
    	 weather = new WeatherRepo("Tallinn");
    	 forecast = new ForecastRepo("Tallinn");
    }
    
    @Test
    public void testIfWeatherRepoRequestCityEqualsResponseCity() {
    	String requestCity = weather.getCurrentCity();
    	
    	weatherAtTheMoment = new WeatherRepo(requestCity);
    	String responseCity = weatherAtTheMoment.getCurrentCity();
    	
    	assertEquals(requestCity, responseCity);
    }
    
    @Test
    public void testIfForecastRepoRequestCityEqualsResponseCity() {
    	String requestCity = forecast.getCurrentCity();
    	
    	forecastAtTheMoment = new ForecastRepo(requestCity);
    	String responseCity = forecastAtTheMoment.getCurrentCity();
    	
    	assertEquals(requestCity, responseCity);
    }
    
    @Test
    public void testIfTemperatureAreExpectedInGivenCity() {
    	Double expectedTemperature = weather.getTemperatureAtTheMoment();
    	
    	weatherAtTheMoment = new WeatherRepo(weather.getCurrentCity());
    	Double responseTemperature = weatherAtTheMoment.getTemperatureAtTheMoment();
    	
    	assertEquals(expectedTemperature, responseTemperature);
    }
    
    @Test
    public void testIfNextDayMaxTempIsExpected() {
    	Double expectedMaxTempNextDay = forecast.getMaxAndMinTemp(1, "max");
    	
    	forecastAtTheMoment = new ForecastRepo(forecast.getCurrentCity());
    	Double responseMaxTempNextDay = forecastAtTheMoment.getMaxAndMinTemp(1, "max");
    	
    	 assertEquals(expectedMaxTempNextDay, responseMaxTempNextDay);
    }
    
    @Test
    public void testIfNextDayMinTempIsExpected() {
    	Double expectedMinTempNextDay = forecast.getMaxAndMinTemp(1, "min");
    	
    	forecastAtTheMoment = new ForecastRepo(forecast.getCurrentCity());
    	Double responseMinTempNextDay = forecastAtTheMoment.getMaxAndMinTemp(1, "min");
    	
    	 assertEquals(expectedMinTempNextDay, responseMinTempNextDay);
    }
    
    @Test
    public void testWeatherWithoutOpenWeatherApi() {
    	WeatherRepo weatherRepo = new WeatherRepo();
    	
    	weatherRepo.setCity("Tallinn");
    	
    	try {
    		weatherRepo.setJsonObject(new JSONObject("{\"coord\":{\"lon\":24.75,\"lat\":59.44},\"weather\":[{\"id\":804,\"main\":\"Clouds\",\"description\":\"overcast clouds\",\"icon\":\"04n\"}],\"base\":\"stations\",\"main\":{\"temp\":-1,\"pressure\":1026,\"humidity\":92,\"temp_min\":-1,\"temp_max\":-1},\"visibility\":10000,\"wind\":{\"speed\":3.6,\"deg\":240},\"clouds\":{\"all\":90},\"dt\":1515567000,\"sys\":{\"type\":1,\"id\":5014,\"message\":0.0022,\"country\":\"EE\",\"sunrise\":1515568244,\"sunset\":1515592014},\"id\":588409,\"name\":\"Tallinn\",\"cod\":200}"));
    	} catch (JSONException e1) {
    		e1.printStackTrace();
    	}
    	
    	assertEquals("Tallinn", weatherRepo.getCurrentCity());
    	assertEquals((Double) (-1.0), weatherRepo.getTemperatureAtTheMoment());
    	assertEquals("lon: 24.75, lat: 59.44", weatherRepo.getCoordinates());
    	
    	
    }
    
    
    
    
    
    
    
    
    

    
    
   
}
