package Test;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import Repo.ForecastRepo;
import Repo.WeatherRepo;

import static org.junit.Assert.*;

import org.junit.Before;

public class WeatherTest {
	
	WeatherRepo weather;
	WeatherRepo weatherAtTheMoment;
	
	ForecastRepo forecast;
	ForecastRepo forecastAtTheMoment;
   
    @Before
    public void startBeforeEeachTest() {
    	 weather = new WeatherRepo("Tallinn");
    	 forecast = new ForecastRepo("Tallinn");
    }
    
    @Test
    public void testIfWeatherRepoRequestCityEqualsResponseCity() {
    	String requestCity = weather.getCurrentCity();
    	
    	weatherAtTheMoment = new WeatherRepo(requestCity);
    	String responseCity = weatherAtTheMoment.getCurrentCity();
    	
    	assertEquals(requestCity, responseCity);
    }
    
    @Test
    public void testIfForecastRepoRequestCityEqualsResponseCity() {
    	String requestCity = forecast.getCurrentCity();
    	
    	forecastAtTheMoment = new ForecastRepo(requestCity);
    	String responseCity = forecastAtTheMoment.getCurrentCity();
    	
    	assertEquals(requestCity, responseCity);
    }
    
    @Test
    public void testIfTemperatureAreExpectedInGivenCity() {
    	Double expectedTemperature = weather.getTemperatureAtTheMoment();
    	
    	weatherAtTheMoment = new WeatherRepo(weather.getCurrentCity());
    	Double responseTemperature = weatherAtTheMoment.getTemperatureAtTheMoment();
    	
    	assertEquals(expectedTemperature, responseTemperature);
    }
    
    @Test
    public void testIfNextDayMaxTempIsExpected() {
    	Double expectedMaxTempNextDay = forecast.getMaxAndMinTemp(1, "max");
    	
    	forecastAtTheMoment = new ForecastRepo(forecast.getCurrentCity());
    	Double responseMaxTempNextDay = forecastAtTheMoment.getMaxAndMinTemp(1, "max");
    	
    	 assertEquals(expectedMaxTempNextDay, responseMaxTempNextDay);
    }
    
    @Test
    public void testIfNextDayMinTempIsExpected() {
    	Double expectedMinTempNextDay = forecast.getMaxAndMinTemp(1, "min");
    	
    	forecastAtTheMoment = new ForecastRepo(forecast.getCurrentCity());
    	Double responseMinTempNextDay = forecastAtTheMoment.getMaxAndMinTemp(1, "min");
    	
    	 assertEquals(expectedMinTempNextDay, responseMinTempNextDay);
    }
    
    
    
    
    
    
    
    
    

    
    
   
}
